displayName: GeoBlock
type: middleware

import: github.com/PascalMinder/geoblock

summary: "block request based on their country of origin"

testData:
  silentStartUp: false
  allowLocalRequests: false
  logLocalRequests: false
  logAllowedRequests: false
  logApiRequests: true
  api: "https://get.geojs.io/v1/ip/country/{ip}"
  apiTimeoutMs: 150
  cacheSize: 15
  forceMonthlyUpdate: true
  allowUnknownCountries: false
  unknownCountryApiResponse: "nil"
  countries:
    - CH
